# Generated by Django 5.1.4 on 2025-01-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_instagram_url_user_instagram_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instagram_name',
            new_name='instagram',
        ),
    ]
