# Generated by Django 5.1.4 on 2025-01-12 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_notification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BringHomeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_buddy_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_buddy_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
