# Generated by Django 5.1.4 on 2025-01-12 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bringhomerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bringhomerequest',
            name='buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_buddy_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
