# Generated by Django 5.1.4 on 2025-01-12 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_instagram_name_user_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='white_list',
            field=models.ManyToManyField(blank=True, related_name='white_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
