# Generated by Django 5.1.4 on 2025-01-12 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bringhomerequest_buddy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bringhomerequest',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.party'),
            preserve_default=False,
        ),
    ]
