# Generated by Django 5.1.4 on 2025-01-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bringhomerequest_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='bringhomerequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
