# Generated by Django 5.1.4 on 2025-01-12 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='brought_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
