# Generated by Django 5.1.4 on 2025-01-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bringhomerequest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bringhomerequest',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests', to='app.party'),
        ),
    ]
